apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    backstage.io/kubernetes-id: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080