apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    backstage.io/kubernetes-id: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070